import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header"; // ヘッダーのインポート
import Footer from "./components/Footer"; // フッターのインポート

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // onSearch関数の定義
  const handleSearch = (term: string) => {
    console.log("Search term:", term);
    // 検索処理をここに追加することができます
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ヘッダーに onSearch プロパティを渡す */}
        <Header onSearch={handleSearch} />

        {/* ページごとのコンテンツ */}
        <main>{children}</main>

        {/* フッターをページ全体の下部に表示 */}
        <Footer />
      </body>
    </html>
  );
}
